kind: pipeline
type: docker
name: build from source
trigger:
    branch:
        - uat
    event:
        - push
steps:
    - name: build app
      image: node:14
      commands:
          - npm i
          - npm run build

    - name: build docker
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo:
              from_secret: docker_repo
          tags:
              - uat

    - name: scp docker docker-compose.yml
      image: appleboy/drone-scp
      settings:
          host:
              from_secret: ssh_host
          username:
              from_secret: ssh_username
          password:
              from_secret: ssh_password
          port: 22
          target: ~/app/kerjaapp/ui
          source: docker-compose.yml

    - name: deploying app
      image: appleboy/drone-ssh
      environment:
          PASSWORD:
              from_secret: docker_password
          USERNAME:
              from_secret: docker_username
          REPO:
              from_secret: docker_repo
      settings:
          host:
              from_secret: ssh_host
          username:
              from_secret: ssh_username
          password:
              from_secret: ssh_password
          port: 22
          envs: [USERNAME, PASSWORD, REPO]
          script:
              - set -e
              - cd ~/app/kerjaapp/ui
              - docker ps -q --filter "name=ka_ui" | grep -q . && docker stop ka_ui || echo Not Found
              - docker ps -q --filter "name=ka_ui" | grep -q . && docker rm ka_ui || echo Not Found
              - docker login -u $USERNAME -p $PASSWORD docker.io
              - docker pull $REPO:uat
              - docker-compose up -d
