version: "3.7"
services:
    karirapp-ui:
        container_name: ka_ui
        ports:
            - "172.17.0.1:8989:80"
        image: talenthrms/karirapp_ui_web:uat
        env_file:
            - ./env
